### ISSUE TITLE
is.Hidden node does not detect hidden in view Detail Groups

### ISSUE THREAD

**Issue by jagostinhoCT** [ksobon/archilab#44]
It detects the elements inside the detail group as hidden but if a list of Detail Groups is given it returns an empty list.

**Comment by ksobon** [comment]
@jagostinhoCT I am sorry, but I don't think archi-lab.net has a node called `IsHidden`. Can you check again to make sure that it is from my package? 

On the other hand, I just went ahead and added one to my package. Here's how it works. I setup a file with bunch of Walls in it. I grouped some walls so that I have a Group of Walls and single Walls. When they are all visible it reports like so: 

![image](https://user-images.githubusercontent.com/529781/55281806-16e1f500-5310-11e9-9d32-e7c254311be6.png)

As you can see above I am getting `true` for all Walls, and the Group that contains Walls. When I hide the Group in the View I am getting this: 

![image](https://user-images.githubusercontent.com/529781/55281830-42fd7600-5310-11e9-8ff3-72fa580758f7.png)

As you can see now I am getting `false` for the Group and individual Walls that were inside of it. This seems to be working how you wanted it based on the description above. Please download the latest version of archi-lab.net to get this node: 

![image](https://user-images.githubusercontent.com/529781/55282336-a2f81a80-5318-11e9-81c0-b6772f262b11.png)

Ps. I changed the name of the node to `Element.IsVisible` instead of `Element.IsHidden` as that makes more sense based on the returned True/False values.

**Comment by jagostinhoCT** [comment]
Hi Konrad.

I must have made some confusion. My apologies.

the latest archi-lab package does not seem to be listed yet on Dynamo's Online Package Search.
![image](https://user-images.githubusercontent.com/43812310/55315850-1d35b580-5465-11e9-9381-20988b3ae712.png)

**Comment by ksobon** [comment]
There is a version published just now: 2019.2.22

![image](https://user-images.githubusercontent.com/529781/56102602-0af35700-5efc-11e9-8dcd-637fe5219bae.png)

Apologies for the delay, but it was actually an issue with the Package Manager. I wasn't able to post new version for a few weeks now.
