### ISSUE TITLE
The google Maps into Revit

### ISSUE THREAD

**Issue by jarods350z** [ksobon/archilab#62]
Just a dumb question. when I follow your way it works perfect in Revit 2021 but it doesn't work for Revit 2019. I get this error for  the node ImageTypeOptions.Create

Warning: ImageTypeOptions.Create operation failed. 
Could not load type 'Autodesk.Revit.DB.ImageTypeOptions' from assembly 'RevitAPI, Version=19.0.0.0, Culture=neutral, PublicKeyToken=null'.

Is this because of the different versions of Dynamo 2019 using Dynamo Core 2.0.4 and Dynamo Revit 2.0.4 Vs 2021 Dynamo Core 2.5.0 and Dynamo Revit 2.5.0

Thanks in advance 
https://archi-lab.net/google-maps-static-api-in-dynamo/

![image](https://user-images.githubusercontent.com/31901707/91586882-04645480-e924-11ea-943e-61b1110c694c.png)

**Comment by ksobon** [comment]
@jarods350z no, that's a limitation of the Revit API. So that ImageTypeOptions object doesn't exist in Revit 2019. I think it was added in later versions when Autodesk enabled PDF imports. 2020 and 2021 will work, but 2019 and earlier won't have that available in the API. 

![image](https://user-images.githubusercontent.com/529781/91593117-34602780-e925-11ea-8d49-b06df061a726.png)

**Comment by jarods350z** [comment]
Ahh well there you go. looks like I have a reason to upgrade to Revit 2021 LOL. Thank you as always!!
