### ISSUE TITLE
Built-in Parameter Vs Parameter (Attachment Justification at Top)

### ISSUE THREAD

**Issue by DillonManning** [ksobon/archilab#9]
Hi there,
I just wanted point out/ get some insight on what is happening with the Get Built in Parameter.   Column "Attachment Justification at Top" values range from 0 - 2 for each value in the Revit drop down. 
The Revit node places an empty value when this parameter doesn't have a value set (column not attached) but the Arhi-lab node places a 0 in said empty value.  
![builtinvsnon](https://user-images.githubusercontent.com/37595457/38509780-27864584-3be0-11e8-880e-f558d9a0de6a.png)

**Comment by ksobon** [comment]
@DillonManning so here's what you are seeing. 

The out of the box node `Element.GetParameterValueByName`: 
* If the value is 0-2, it's indicating one of the dropdown selections like you mentioned above. 
* If the value is just empty then it means that the column IS NOT attached at top at all. There is no parameter to report. 

The Archi-lab.net BuiltInParameter node works like this: 
* since it uses BuiltInParameters, these ALWAYS exist on the element. It will not report a non existing value. Also since all BIP have default values and in this case it's 0, then it reports the 0 value. Its a similar behavior to what you might have noticed with Checkbox parameters. By default they are greyed out, and checked. Per se, that parameter was not assigned yet, but Revit has to store something in there so it assigns a default value of True (1) and if you use something like a View Filter to filter by a checkbox value that was not assigned it will think that it's True (1) since that's default. Same thing happens here. 
* This basically results in all columns saying that they have attached state of 0 which clearly is not true. I added an additional check here to work around that. It should work like this: 

![image](https://user-images.githubusercontent.com/529781/38511304-c535d320-3bf5-11e8-9e9f-a1e6db0adf71.png)
